/** Módulos cadastrados no painel Master via master_feature_toggles. */
export const MASTER_FEATURE_TOGGLE_KEYS = [
  'audit_logs',
  'bank_credentials',
  'broadcasts',
  'chip_monitor',
  'chips',
  'commission_reports',
  'commissions',
  'commissions_v2',
  'contract_template',
  'corban_assets',
  'corban_config',
  'corban_dashboard',
  'corban_fgts',
  'corban_propostas',
  'dashboard',
  'hr',
  'integrations',
  'internal_chat',
  'kanban',
  'leads',
  'links',
  'partners',
  'performance',
  'permissions',
  'product_info',
  'queue',
  'quick_replies',
  'remote_assistance',
  'seller_fgts',
  'seller_propostas',
  'settings_warming',
  'templates',
  'tickets',
  'users',
  'v8_simulador',
  'warming_reports',
  'webhooks',
  'whatsapp',
] as const;

/** Maps feature_key → route path(s). */
export const FEATURE_ROUTE_MAP: Record<string, string[]> = {
  dashboard: ['/dashboard'],
  chips: ['/chips'],
  settings_warming: ['/settingsaquecimento'],
  warming_reports: ['/admin/warming-reports'],
  users: ['/admin/users'],
  leads: ['/admin/leads'],
  performance: ['/admin/performance'],
  kanban: ['/admin/kanban'],
  product_info: ['/admin/product-info'],
  commissions: ['/admin/commissions'],
  commission_reports: ['/admin/commission-reports'],
  chip_monitor: ['/admin/chip-monitor'],
  queue: ['/admin/queue'],
  webhooks: ['/admin/webhooks'],
  templates: ['/admin/templates'],
  quick_replies: ['/admin/quick-replies'],
  tickets: ['/admin/tickets'],
  internal_chat: ['/chat'],
  links: ['/admin/links'],
  remote_assistance: ['/admin/remote'],
  audit_logs: ['/admin/audit-logs'],
  permissions: ['/admin/permissions'],
  corban_dashboard: ['/admin/corban'],
  corban_propostas: ['/admin/corban/propostas'],
  corban_fgts: ['/admin/corban/fgts'],
  corban_assets: ['/admin/corban/assets'],
  corban_config: ['/admin/corban/config'],
  seller_propostas: ['/corban/propostas'],
  seller_fgts: ['/corban/fgts'],
  whatsapp: ['/whatsapp'],
  master_admin: ['/admin/master'],
  bank_credentials: ['/admin/bancos'],
  partners: ['/admin/parceiros', '/admin/parceiros/template', '/admin/parceiros/:id'],
  contract_template: ['/admin/parceiros/template'],
  broadcasts: ['/admin/broadcasts'],
  hr: ['/admin/hr'],
  v8_simulador: ['/admin/v8-simulador'],
  commissions_v2: ['/admin/commissions-v2'],
  integrations: ['/admin/integrations'],
};

export const ROUTE_FEATURE_MAP: Record<string, string> = Object.entries(FEATURE_ROUTE_MAP).reduce(
  (acc, [key, routes]) => {
    routes.forEach((route) => {
      acc[route] = key;
    });
    return acc;
  },
  {} as Record<string, string>,
);
