project_id = "sibfqmzsnftscnlyuwiu"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.instance-maintenance]
verify_jwt = false

[functions.queue-processor]
verify_jwt = false

[functions.uazapi-api]
verify_jwt = false

[functions.update-user-role]
verify_jwt = false

[functions.warming-engine]
verify_jwt = false

[functions.sync-history]
verify_jwt = false

[functions.chip-health-check]
verify_jwt = false

[functions.corban-api]
verify_jwt = false

[functions.corban-status-sync]
verify_jwt = false

[functions.clicksign-api]
verify_jwt = false

[functions.clicksign-webhook]
verify_jwt = false
