project_id = "yutagjarhxpcqerhqdha"

[functions.create-user]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.warming-engine]
verify_jwt = false

[functions.update-user-role]
verify_jwt = false

[functions.uazapi-api]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.queue-processor]
verify_jwt = false